# Auto-generated at IST: 2026-09-03 19:15:16+0530
# Source universe: filtered_stocks_MIS_v2.py (1,279 symbols)
# Bucket membership: official NSE index constituent CSVs (niftyindices.com)
# F&O flag: live Kite instruments('NFO') FUT underlyings
# Buckets: 15 sectoral + 7 thematic + 1 OTHER_FNO
# Universe: 287 symbols (210 F&O, 77 cash-only)
# Removed from v2: 996 symbols in no NSE index and with no futures contract
#
# Retention rule: a symbol is kept if it belongs to at least one NSE
# sectoral/thematic index, OR has a live futures contract. Symbols with
# neither are dropped. This keeps every tradeable F&O name (43 of which
# sit in no NSE index) while discarding illiquid unclassified smallcaps.
#
# Known symbol correction applied by the live sources: LTIMindtree now
# trades as LTM on NSE; LTIM no longer exists. v2 and configs/
# sector_etf_map.json both still carry the stale LTIM symbol.
"""Sector/thematic bucketed NSE universe with F&O flags.

Import patterns::

    from filtered_stocks_MIS_v3 import selected_stocks        # flat set, v2-compatible
    from filtered_stocks_MIS_v3 import SECTORAL_BUCKETS, THEMATIC_BUCKETS
    from filtered_stocks_MIS_v3 import FNO_STOCKS, stocks_in, fno_in, non_fno_in

    stocks_in('NIFTY_PHARMA')                 # every constituent
    fno_in('NIFTY_PHARMA')                    # F&O-tradeable subset
    non_fno_in('NIFTY_PHARMA')                # cash-only subset
    PRIMARY_SECTOR['RELIANCE']                # single sector per symbol
    MEMBERSHIP['RELIANCE']                    # every bucket it belongs to
"""

from __future__ import annotations

GENERATED_AT_IST = '2026-09-03 19:15:16+0530'

# --------------------------------------------------------------------------
# F&O universe (live Kite NFO futures underlyings; index futures excluded)
# --------------------------------------------------------------------------
FNO_STOCKS = frozenset({
        '360ONE', 'ABB', 'ABCAPITAL', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN',
        'ADANIPORTS', 'ADANIPOWER', 'ALKEM', 'AMBER', 'AMBUJACEM', 'ANGELONE',
        'APLAPOLLO', 'APOLLOHOSP', 'ASHOKLEY', 'ASIANPAINT', 'ASTRAL', 'ATHERENERG',
        'AUBANK', 'AUROPHARMA', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAJHLDNG',
        'BAJFINANCE', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'BDL', 'BEL',
        'BHARATFORG', 'BHARTIARTL', 'BHEL', 'BIOCON', 'BLUESTARCO', 'BOSCHLTD',
        'BPCL', 'BRITANNIA', 'BSE', 'CAMS', 'CANBK', 'CDSL',
        'CGPOWER', 'CHOLAFIN', 'CIPLA', 'COALINDIA', 'COCHINSHIP', 'COFORGE',
        'COLPAL', 'CONCOR', 'CROMPTON', 'CUMMINSIND', 'DABUR', 'DELHIVERY',
        'DIVISLAB', 'DIXON', 'DLF', 'DMART', 'DRREDDY', 'EICHERMOT',
        'ETERNAL', 'FEDERALBNK', 'FORCEMOT', 'FORTIS', 'GAIL', 'GLENMARK',
        'GMRAIRPORT', 'GODFRYPHLP', 'GODREJCP', 'GODREJPROP', 'GRASIM', 'GVT&D',
        'HAL', 'HAVELLS', 'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE',
        'HEROMOTOCO', 'HINDALCO', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'HYUNDAI',
        'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'IDEA', 'IDFCFIRSTB', 'IEX',
        'INDHOTEL', 'INDIANB', 'INDIGO', 'INDUSINDBK', 'INDUSTOWER', 'INFY',
        'INOXWIND', 'IOC', 'IREDA', 'IRFC', 'ITC', 'JINDALSTEL',
        'JIOFIN', 'JSWENERGY', 'JSWSTEEL', 'JUBLFOOD', 'KALYANKJIL', 'KAYNES',
        'KEI', 'KFINTECH', 'KOTAKBANK', 'KPITTECH', 'LAURUSLABS', 'LICHSGFIN',
        'LICI', 'LODHA', 'LT', 'LTF', 'LTM', 'LUPIN',
        'M&M', 'MAHABANK', 'MANAPPURAM', 'MANKIND', 'MARICO', 'MARUTI',
        'MAXHEALTH', 'MAZDOCK', 'MCX', 'MFSL', 'MOTHERSON', 'MOTILALOFS',
        'MPHASIS', 'MUTHOOTFIN', 'NAM-INDIA', 'NATIONALUM', 'NAUKRI', 'NBCC',
        'NESTLEIND', 'NHPC', 'NMDC', 'NTPC', 'NYKAA', 'OBEROIRLTY',
        'OFSS', 'OIL', 'ONGC', 'PAGEIND', 'PATANJALI', 'PAYTM',
        'PERSISTENT', 'PETRONET', 'PFC', 'PGEL', 'PHOENIXLTD', 'PIDILITIND',
        'PIIND', 'PNB', 'PNBHOUSING', 'POLICYBZR', 'POLYCAB', 'POWERGRID',
        'POWERINDIA', 'PREMIERENE', 'PRESTIGE', 'RADICO', 'RBLBANK', 'RECLTD',
        'RELIANCE', 'RVNL', 'SAGILITY', 'SAIL', 'SBICARD', 'SBILIFE',
        'SBIN', 'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SOLARINDS', 'SONACOMS',
        'SRF', 'SUNPHARMA', 'SUPREMEIND', 'SUZLON', 'SWIGGY', 'TATACONSUM',
        'TATAELXSI', 'TATAPOWER', 'TATASTEEL', 'TCS', 'TECHM', 'TIINDIA',
        'TITAN', 'TMPV', 'TORNTPHARM', 'TRENT', 'TVSMOTOR', 'ULTRACEMCO',
        'UNIONBANK', 'UNITDSPR', 'UNOMINDA', 'UPL', 'VBL', 'VEDL',
        'VMM', 'VOLTAS', 'WAAREEENER', 'WIPRO', 'YESBANK', 'ZYDUSLIFE',
    })

# --------------------------------------------------------------------------
# Sectoral buckets - complete official NSE index membership
# --------------------------------------------------------------------------
SECTORAL_BUCKETS: dict[str, frozenset[str]] = {
    # https://niftyindices.com/IndexConstituent/ind_niftyautolist.csv
    'NIFTY_AUTO': frozenset({
        'ASHOKLEY', 'BAJAJ-AUTO', 'BHARATFORG', 'BOSCHLTD', 'EICHERMOT', 'EXIDEIND',
        'HEROMOTOCO', 'M&M', 'MARUTI', 'MOTHERSON', 'SONACOMS', 'TIINDIA',
        'TMPV', 'TVSMOTOR', 'UNOMINDA',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftybanklist.csv
    'NIFTY_BANK': frozenset({
        'AUBANK', 'AXISBANK', 'BANKBARODA', 'CANBK', 'FEDERALBNK', 'HDFCBANK',
        'ICICIBANK', 'IDFCFIRSTB', 'INDUSINDBK', 'KOTAKBANK', 'PNB', 'SBIN',
        'UNIONBANK', 'YESBANK',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftychemicalslist.csv
    'NIFTY_CHEMICALS': frozenset({
        'AARTIIND', 'ATUL', 'BAYERCROP', 'CHAMBLFERT', 'COROMANDEL', 'DEEPAKNTR',
        'EIDPARRY', 'FLUOROCHEM', 'GNFC', 'HSCL', 'LINDEINDIA', 'NAVINFLUOR',
        'PCBL', 'PIDILITIND', 'PIIND', 'SOLARINDS', 'SRF', 'SUMICHEM',
        'TATACHEM', 'UPL',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyconsumerdurableslist.csv
    'NIFTY_CONSUMER_DURABLES': frozenset({
        'AMBER', 'BATAINDIA', 'BLUESTARCO', 'CROMPTON', 'DIXON', 'HAVELLS',
        'KAJARIACER', 'KALYANKJIL', 'LGEINDIA', 'PGEL', 'TITAN', 'VOLTAS',
        'WHIRLPOOL',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyfinancialservices25-50list.csv
    'NIFTY_FINANCIAL_SERVICES_25_50': frozenset({
        'AXISBANK', 'BAJAJFINSV', 'BAJFINANCE', 'BSE', 'CHOLAFIN', 'HDFCBANK',
        'HDFCLIFE', 'ICICIBANK', 'ICICIGI', 'JIOFIN', 'KOTAKBANK', 'LICHSGFIN',
        'MFSL', 'MUTHOOTFIN', 'PFC', 'RECLTD', 'SBICARD', 'SBILIFE',
        'SBIN', 'SHRIRAMFIN',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyfmcglist.csv
    'NIFTY_FMCG': frozenset({
        'BRITANNIA', 'COLPAL', 'DABUR', 'EMAMILTD', 'GODREJCP', 'HINDUNILVR',
        'ITC', 'MARICO', 'NESTLEIND', 'PATANJALI', 'RADICO', 'TATACONSUM',
        'UBL', 'UNITDSPR', 'VBL',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyhealthcarelist.csv
    'NIFTY_HEALTHCARE': frozenset({
        'ABBOTINDIA', 'ALKEM', 'APOLLOHOSP', 'AUROPHARMA', 'BIOCON', 'CIPLA',
        'DIVISLAB', 'DRREDDY', 'FORTIS', 'GLENMARK', 'IPCALAB', 'LAURUSLABS',
        'LUPIN', 'MANKIND', 'MAXHEALTH', 'PPLPHARMA', 'SUNPHARMA', 'SYNGENE',
        'TORNTPHARM', 'ZYDUSLIFE',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyitlist.csv
    'NIFTY_IT': frozenset({
        'COFORGE', 'HCLTECH', 'INFY', 'LTM', 'MPHASIS', 'OFSS',
        'PERSISTENT', 'TCS', 'TECHM', 'WIPRO',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftymedialist.csv
    'NIFTY_MEDIA': frozenset({
        'DBCORP', 'HATHWAY', 'NAZARA', 'NETWORK18', 'PFOCUS', 'PVRINOX',
        'SAREGAMA', 'SUNTV', 'TIPSMUSIC', 'ZEEL',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftymetallist.csv
    'NIFTY_METAL': frozenset({
        'ADANIENT', 'APLAPOLLO', 'HINDALCO', 'HINDCOPPER', 'HINDZINC', 'JINDALSTEL',
        'JSL', 'JSWSTEEL', 'LLOYDSME', 'NATIONALUM', 'NMDC', 'SAIL',
        'TATASTEEL', 'VEDL', 'WELCORP',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyoilgaslist.csv
    'NIFTY_OIL_AND_GAS': frozenset({
        'AEGISLOG', 'AEGISVOPAK', 'ATGL', 'BPCL', 'CASTROLIND', 'CHENNPETRO',
        'GAIL', 'HINDPETRO', 'IGL', 'IOC', 'MGL', 'OIL',
        'ONGC', 'PETRONET', 'RELIANCE',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftypharmalist.csv
    'NIFTY_PHARMA': frozenset({
        'ABBOTINDIA', 'AJANTPHARM', 'ALKEM', 'AUROPHARMA', 'BIOCON', 'CIPLA',
        'DIVISLAB', 'DRREDDY', 'GLAND', 'GLENMARK', 'IPCALAB', 'LAURUSLABS',
        'LUPIN', 'MANKIND', 'PPLPHARMA', 'SAILIFE', 'SUNPHARMA', 'TORNTPHARM',
        'WOCKPHARMA', 'ZYDUSLIFE',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyprivatebanklist.csv
    'NIFTY_PRIVATE_BANK': frozenset({
        'AXISBANK', 'BANDHANBNK', 'FEDERALBNK', 'HDFCBANK', 'ICICIBANK', 'IDFCFIRSTB',
        'INDUSINDBK', 'KOTAKBANK', 'RBLBANK', 'YESBANK',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftypsubanklist.csv
    'NIFTY_PSU_BANK': frozenset({
        'BANKBARODA', 'BANKINDIA', 'CANBK', 'CENTRALBK', 'INDIANB', 'IOB',
        'MAHABANK', 'PNB', 'PSB', 'SBIN', 'UCOBANK', 'UNIONBANK',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyrealtylist.csv
    'NIFTY_REALTY': frozenset({
        'ABREL', 'ANANTRAJ', 'BRIGADE', 'DLF', 'GODREJPROP', 'LODHA',
        'OBEROIRLTY', 'PHOENIXLTD', 'PRESTIGE', 'SOBHA',
    }),
}

# --------------------------------------------------------------------------
# Thematic buckets - complete official NSE index membership
# --------------------------------------------------------------------------
THEMATIC_BUCKETS: dict[str, frozenset[str]] = {
    # https://niftyindices.com/IndexConstituent/ind_niftycommoditieslist.csv
    'NIFTY_COMMODITIES': frozenset({
        'ADANIENSOL', 'ADANIGREEN', 'ADANIPOWER', 'AMBUJACEM', 'APLAPOLLO', 'BPCL',
        'COALINDIA', 'GRASIM', 'HINDALCO', 'HINDPETRO', 'IOC', 'JINDALSTEL',
        'JSWENERGY', 'JSWSTEEL', 'NHPC', 'NMDC', 'NTPC', 'OIL',
        'ONGC', 'PIDILITIND', 'PIIND', 'RELIANCE', 'SHREECEM', 'SRF',
        'TATAPOWER', 'TATASTEEL', 'TORNTPOWER', 'ULTRACEMCO', 'UPL', 'VEDL',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyconsumptionlist.csv
    'NIFTY_INDIA_CONSUMPTION': frozenset({
        'ADANIPOWER', 'APOLLOHOSP', 'ASIANPAINT', 'BAJAJ-AUTO', 'BHARTIARTL', 'BRITANNIA',
        'DIXON', 'DLF', 'DMART', 'EICHERMOT', 'ETERNAL', 'GODREJCP',
        'HAVELLS', 'HEROMOTOCO', 'HINDUNILVR', 'INDHOTEL', 'INDIGO', 'ITC',
        'M&M', 'MARUTI', 'MAXHEALTH', 'NAUKRI', 'NESTLEIND', 'TATACONSUM',
        'TATAPOWER', 'TITAN', 'TRENT', 'TVSMOTOR', 'UNITDSPR', 'VBL',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftycpselist.csv
    'NIFTY_CPSE': frozenset({
        'BEL', 'COALINDIA', 'COCHINSHIP', 'NBCC', 'NHPC', 'NLCINDIA',
        'NTPC', 'OIL', 'ONGC', 'POWERGRID', 'SJVN',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyenergylist.csv
    'NIFTY_ENERGY': frozenset({
        'ABB', 'ADANIENSOL', 'ADANIGREEN', 'ADANIPOWER', 'AEGISLOG', 'ATGL',
        'BHEL', 'BPCL', 'CASTROLIND', 'CESC', 'CGPOWER', 'COALINDIA',
        'ENRIN', 'GAIL', 'GVT&D', 'HINDPETRO', 'IGL', 'INOXWIND',
        'IOC', 'JPPOWER', 'JSWENERGY', 'MGL', 'NAVA', 'NHPC',
        'NLCINDIA', 'NTPC', 'NTPCGREEN', 'OIL', 'ONGC', 'PETRONET',
        'POWERGRID', 'POWERINDIA', 'RELIANCE', 'RPOWER', 'SIEMENS', 'SJVN',
        'SUZLON', 'TATAPOWER', 'THERMAX', 'TORNTPOWER',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftyinfralist.csv
    'NIFTY_INFRASTRUCTURE': frozenset({
        'ADANIGREEN', 'ADANIPORTS', 'AMBUJACEM', 'APOLLOHOSP', 'ASHOKLEY', 'BHARATFORG',
        'BHARTIARTL', 'BPCL', 'CGPOWER', 'CUMMINSIND', 'DLF', 'FORTIS',
        'GAIL', 'GRASIM', 'HINDPETRO', 'INDHOTEL', 'INDIGO', 'INDUSTOWER',
        'IOC', 'LT', 'MAXHEALTH', 'MOTHERSON', 'NTPC', 'ONGC',
        'POWERGRID', 'RELIANCE', 'SHREECEM', 'SUZLON', 'TATAPOWER', 'ULTRACEMCO',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftymnclist.csv
    'NIFTY_MNC': frozenset({
        '3MINDIA', 'ABB', 'ABBOTINDIA', 'AMBUJACEM', 'ASHOKLEY', 'AWL',
        'BOSCHLTD', 'BRITANNIA', 'CASTROLIND', 'COHANCE', 'COLPAL', 'CRISIL',
        'CUMMINSIND', 'ENRIN', 'ESCORTS', 'GLAND', 'HINDUNILVR', 'HYUNDAI',
        'LINDEINDIA', 'MARUTI', 'NAM-INDIA', 'NESTLEIND', 'OFSS', 'POWERINDIA',
        'SCHAEFFLER', 'SIEMENS', 'TIMKEN', 'UBL', 'UNITDSPR', 'VEDL',
    }),
    # https://niftyindices.com/IndexConstituent/ind_niftypselist.csv
    'NIFTY_PSE': frozenset({
        'BEL', 'BHEL', 'BPCL', 'COALINDIA', 'CONCOR', 'GAIL',
        'HAL', 'HINDPETRO', 'IOC', 'IRCTC', 'IRFC', 'NHPC',
        'NMDC', 'NTPC', 'OIL', 'ONGC', 'PFC', 'POWERGRID',
        'RECLTD', 'RVNL',
    }),
}

# --------------------------------------------------------------------------
# F&O underlyings that belong to no NSE sectoral or thematic index.
# Kept because they are tradeable; several are traded by the FnO strategies.
# --------------------------------------------------------------------------
OTHER_FNO: frozenset[str] = frozenset({
        '360ONE', 'ABCAPITAL', 'ANGELONE', 'ASTRAL', 'ATHERENERG', 'BAJAJHLDNG',
        'BDL', 'CAMS', 'CDSL', 'DELHIVERY', 'FORCEMOT', 'GMRAIRPORT',
        'GODFRYPHLP', 'HDFCAMC', 'ICICIPRULI', 'IDEA', 'IEX', 'IREDA',
        'JUBLFOOD', 'KAYNES', 'KEI', 'KFINTECH', 'KPITTECH', 'LICI',
        'LTF', 'MANAPPURAM', 'MAZDOCK', 'MCX', 'MOTILALOFS', 'NYKAA',
        'PAGEIND', 'PAYTM', 'PNBHOUSING', 'POLICYBZR', 'POLYCAB', 'PREMIERENE',
        'SAGILITY', 'SUPREMEIND', 'SWIGGY', 'TATAELXSI', 'VMM', 'WAAREEENER',
    })

ALL_BUCKETS: dict[str, frozenset[str]] = {
    **SECTORAL_BUCKETS,
    **THEMATIC_BUCKETS,
    'OTHER_FNO': OTHER_FNO,
}

BUCKET_KIND: dict[str, str] = {
    'NIFTY_AUTO': 'SECTORAL',
    'NIFTY_BANK': 'SECTORAL',
    'NIFTY_CHEMICALS': 'SECTORAL',
    'NIFTY_CONSUMER_DURABLES': 'SECTORAL',
    'NIFTY_FINANCIAL_SERVICES_25_50': 'SECTORAL',
    'NIFTY_FMCG': 'SECTORAL',
    'NIFTY_HEALTHCARE': 'SECTORAL',
    'NIFTY_IT': 'SECTORAL',
    'NIFTY_MEDIA': 'SECTORAL',
    'NIFTY_METAL': 'SECTORAL',
    'NIFTY_OIL_AND_GAS': 'SECTORAL',
    'NIFTY_PHARMA': 'SECTORAL',
    'NIFTY_PRIVATE_BANK': 'SECTORAL',
    'NIFTY_PSU_BANK': 'SECTORAL',
    'NIFTY_REALTY': 'SECTORAL',
    'NIFTY_COMMODITIES': 'THEMATIC',
    'NIFTY_INDIA_CONSUMPTION': 'THEMATIC',
    'NIFTY_CPSE': 'THEMATIC',
    'NIFTY_ENERGY': 'THEMATIC',
    'NIFTY_INFRASTRUCTURE': 'THEMATIC',
    'NIFTY_MNC': 'THEMATIC',
    'NIFTY_PSE': 'THEMATIC',
    'OTHER_FNO': 'OTHER',
}

# Flat universe. Name kept as `selected_stocks` so v3 is a drop-in
# replacement for `from filtered_stocks_MIS_v2 import selected_stocks`.
selected_stocks: frozenset[str] = frozenset().union(*ALL_BUCKETS.values())

# One sector per symbol. Sub-sector indices beat their parent (PSU/Private
# Bank before Bank, Pharma before Healthcare); sectoral beats thematic;
# unclassified F&O names resolve to OTHER_FNO.
PRIMARY_SECTOR: dict[str, str] = {
    '360ONE': 'OTHER_FNO',
    '3MINDIA': 'NIFTY_MNC',
    'AARTIIND': 'NIFTY_CHEMICALS',
    'ABB': 'NIFTY_ENERGY',
    'ABBOTINDIA': 'NIFTY_PHARMA',
    'ABCAPITAL': 'OTHER_FNO',
    'ABREL': 'NIFTY_REALTY',
    'ADANIENSOL': 'NIFTY_COMMODITIES',
    'ADANIENT': 'NIFTY_METAL',
    'ADANIGREEN': 'NIFTY_COMMODITIES',
    'ADANIPORTS': 'NIFTY_INFRASTRUCTURE',
    'ADANIPOWER': 'NIFTY_COMMODITIES',
    'AEGISLOG': 'NIFTY_OIL_AND_GAS',
    'AEGISVOPAK': 'NIFTY_OIL_AND_GAS',
    'AJANTPHARM': 'NIFTY_PHARMA',
    'ALKEM': 'NIFTY_PHARMA',
    'AMBER': 'NIFTY_CONSUMER_DURABLES',
    'AMBUJACEM': 'NIFTY_COMMODITIES',
    'ANANTRAJ': 'NIFTY_REALTY',
    'ANGELONE': 'OTHER_FNO',
    'APLAPOLLO': 'NIFTY_METAL',
    'APOLLOHOSP': 'NIFTY_HEALTHCARE',
    'ASHOKLEY': 'NIFTY_AUTO',
    'ASIANPAINT': 'NIFTY_INDIA_CONSUMPTION',
    'ASTRAL': 'OTHER_FNO',
    'ATGL': 'NIFTY_OIL_AND_GAS',
    'ATHERENERG': 'OTHER_FNO',
    'ATUL': 'NIFTY_CHEMICALS',
    'AUBANK': 'NIFTY_BANK',
    'AUROPHARMA': 'NIFTY_PHARMA',
    'AWL': 'NIFTY_MNC',
    'AXISBANK': 'NIFTY_PRIVATE_BANK',
    'BAJAJ-AUTO': 'NIFTY_AUTO',
    'BAJAJFINSV': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'BAJAJHLDNG': 'OTHER_FNO',
    'BAJFINANCE': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'BANDHANBNK': 'NIFTY_PRIVATE_BANK',
    'BANKBARODA': 'NIFTY_PSU_BANK',
    'BANKINDIA': 'NIFTY_PSU_BANK',
    'BATAINDIA': 'NIFTY_CONSUMER_DURABLES',
    'BAYERCROP': 'NIFTY_CHEMICALS',
    'BDL': 'OTHER_FNO',
    'BEL': 'NIFTY_CPSE',
    'BHARATFORG': 'NIFTY_AUTO',
    'BHARTIARTL': 'NIFTY_INDIA_CONSUMPTION',
    'BHEL': 'NIFTY_ENERGY',
    'BIOCON': 'NIFTY_PHARMA',
    'BLUESTARCO': 'NIFTY_CONSUMER_DURABLES',
    'BOSCHLTD': 'NIFTY_AUTO',
    'BPCL': 'NIFTY_OIL_AND_GAS',
    'BRIGADE': 'NIFTY_REALTY',
    'BRITANNIA': 'NIFTY_FMCG',
    'BSE': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'CAMS': 'OTHER_FNO',
    'CANBK': 'NIFTY_PSU_BANK',
    'CASTROLIND': 'NIFTY_OIL_AND_GAS',
    'CDSL': 'OTHER_FNO',
    'CENTRALBK': 'NIFTY_PSU_BANK',
    'CESC': 'NIFTY_ENERGY',
    'CGPOWER': 'NIFTY_ENERGY',
    'CHAMBLFERT': 'NIFTY_CHEMICALS',
    'CHENNPETRO': 'NIFTY_OIL_AND_GAS',
    'CHOLAFIN': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'CIPLA': 'NIFTY_PHARMA',
    'COALINDIA': 'NIFTY_COMMODITIES',
    'COCHINSHIP': 'NIFTY_CPSE',
    'COFORGE': 'NIFTY_IT',
    'COHANCE': 'NIFTY_MNC',
    'COLPAL': 'NIFTY_FMCG',
    'CONCOR': 'NIFTY_PSE',
    'COROMANDEL': 'NIFTY_CHEMICALS',
    'CRISIL': 'NIFTY_MNC',
    'CROMPTON': 'NIFTY_CONSUMER_DURABLES',
    'CUMMINSIND': 'NIFTY_INFRASTRUCTURE',
    'DABUR': 'NIFTY_FMCG',
    'DBCORP': 'NIFTY_MEDIA',
    'DEEPAKNTR': 'NIFTY_CHEMICALS',
    'DELHIVERY': 'OTHER_FNO',
    'DIVISLAB': 'NIFTY_PHARMA',
    'DIXON': 'NIFTY_CONSUMER_DURABLES',
    'DLF': 'NIFTY_REALTY',
    'DMART': 'NIFTY_INDIA_CONSUMPTION',
    'DRREDDY': 'NIFTY_PHARMA',
    'EICHERMOT': 'NIFTY_AUTO',
    'EIDPARRY': 'NIFTY_CHEMICALS',
    'EMAMILTD': 'NIFTY_FMCG',
    'ENRIN': 'NIFTY_ENERGY',
    'ESCORTS': 'NIFTY_MNC',
    'ETERNAL': 'NIFTY_INDIA_CONSUMPTION',
    'EXIDEIND': 'NIFTY_AUTO',
    'FEDERALBNK': 'NIFTY_PRIVATE_BANK',
    'FLUOROCHEM': 'NIFTY_CHEMICALS',
    'FORCEMOT': 'OTHER_FNO',
    'FORTIS': 'NIFTY_HEALTHCARE',
    'GAIL': 'NIFTY_OIL_AND_GAS',
    'GLAND': 'NIFTY_PHARMA',
    'GLENMARK': 'NIFTY_PHARMA',
    'GMRAIRPORT': 'OTHER_FNO',
    'GNFC': 'NIFTY_CHEMICALS',
    'GODFRYPHLP': 'OTHER_FNO',
    'GODREJCP': 'NIFTY_FMCG',
    'GODREJPROP': 'NIFTY_REALTY',
    'GRASIM': 'NIFTY_COMMODITIES',
    'GVT&D': 'NIFTY_ENERGY',
    'HAL': 'NIFTY_PSE',
    'HATHWAY': 'NIFTY_MEDIA',
    'HAVELLS': 'NIFTY_CONSUMER_DURABLES',
    'HCLTECH': 'NIFTY_IT',
    'HDFCAMC': 'OTHER_FNO',
    'HDFCBANK': 'NIFTY_PRIVATE_BANK',
    'HDFCLIFE': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'HEROMOTOCO': 'NIFTY_AUTO',
    'HINDALCO': 'NIFTY_METAL',
    'HINDCOPPER': 'NIFTY_METAL',
    'HINDPETRO': 'NIFTY_OIL_AND_GAS',
    'HINDUNILVR': 'NIFTY_FMCG',
    'HINDZINC': 'NIFTY_METAL',
    'HSCL': 'NIFTY_CHEMICALS',
    'HYUNDAI': 'NIFTY_MNC',
    'ICICIBANK': 'NIFTY_PRIVATE_BANK',
    'ICICIGI': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'ICICIPRULI': 'OTHER_FNO',
    'IDEA': 'OTHER_FNO',
    'IDFCFIRSTB': 'NIFTY_PRIVATE_BANK',
    'IEX': 'OTHER_FNO',
    'IGL': 'NIFTY_OIL_AND_GAS',
    'INDHOTEL': 'NIFTY_INDIA_CONSUMPTION',
    'INDIANB': 'NIFTY_PSU_BANK',
    'INDIGO': 'NIFTY_INDIA_CONSUMPTION',
    'INDUSINDBK': 'NIFTY_PRIVATE_BANK',
    'INDUSTOWER': 'NIFTY_INFRASTRUCTURE',
    'INFY': 'NIFTY_IT',
    'INOXWIND': 'NIFTY_ENERGY',
    'IOB': 'NIFTY_PSU_BANK',
    'IOC': 'NIFTY_OIL_AND_GAS',
    'IPCALAB': 'NIFTY_PHARMA',
    'IRCTC': 'NIFTY_PSE',
    'IREDA': 'OTHER_FNO',
    'IRFC': 'NIFTY_PSE',
    'ITC': 'NIFTY_FMCG',
    'JINDALSTEL': 'NIFTY_METAL',
    'JIOFIN': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'JPPOWER': 'NIFTY_ENERGY',
    'JSL': 'NIFTY_METAL',
    'JSWENERGY': 'NIFTY_COMMODITIES',
    'JSWSTEEL': 'NIFTY_METAL',
    'JUBLFOOD': 'OTHER_FNO',
    'KAJARIACER': 'NIFTY_CONSUMER_DURABLES',
    'KALYANKJIL': 'NIFTY_CONSUMER_DURABLES',
    'KAYNES': 'OTHER_FNO',
    'KEI': 'OTHER_FNO',
    'KFINTECH': 'OTHER_FNO',
    'KOTAKBANK': 'NIFTY_PRIVATE_BANK',
    'KPITTECH': 'OTHER_FNO',
    'LAURUSLABS': 'NIFTY_PHARMA',
    'LGEINDIA': 'NIFTY_CONSUMER_DURABLES',
    'LICHSGFIN': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'LICI': 'OTHER_FNO',
    'LINDEINDIA': 'NIFTY_CHEMICALS',
    'LLOYDSME': 'NIFTY_METAL',
    'LODHA': 'NIFTY_REALTY',
    'LT': 'NIFTY_INFRASTRUCTURE',
    'LTF': 'OTHER_FNO',
    'LTM': 'NIFTY_IT',
    'LUPIN': 'NIFTY_PHARMA',
    'M&M': 'NIFTY_AUTO',
    'MAHABANK': 'NIFTY_PSU_BANK',
    'MANAPPURAM': 'OTHER_FNO',
    'MANKIND': 'NIFTY_PHARMA',
    'MARICO': 'NIFTY_FMCG',
    'MARUTI': 'NIFTY_AUTO',
    'MAXHEALTH': 'NIFTY_HEALTHCARE',
    'MAZDOCK': 'OTHER_FNO',
    'MCX': 'OTHER_FNO',
    'MFSL': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'MGL': 'NIFTY_OIL_AND_GAS',
    'MOTHERSON': 'NIFTY_AUTO',
    'MOTILALOFS': 'OTHER_FNO',
    'MPHASIS': 'NIFTY_IT',
    'MUTHOOTFIN': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'NAM-INDIA': 'NIFTY_MNC',
    'NATIONALUM': 'NIFTY_METAL',
    'NAUKRI': 'NIFTY_INDIA_CONSUMPTION',
    'NAVA': 'NIFTY_ENERGY',
    'NAVINFLUOR': 'NIFTY_CHEMICALS',
    'NAZARA': 'NIFTY_MEDIA',
    'NBCC': 'NIFTY_CPSE',
    'NESTLEIND': 'NIFTY_FMCG',
    'NETWORK18': 'NIFTY_MEDIA',
    'NHPC': 'NIFTY_COMMODITIES',
    'NLCINDIA': 'NIFTY_CPSE',
    'NMDC': 'NIFTY_METAL',
    'NTPC': 'NIFTY_COMMODITIES',
    'NTPCGREEN': 'NIFTY_ENERGY',
    'NYKAA': 'OTHER_FNO',
    'OBEROIRLTY': 'NIFTY_REALTY',
    'OFSS': 'NIFTY_IT',
    'OIL': 'NIFTY_OIL_AND_GAS',
    'ONGC': 'NIFTY_OIL_AND_GAS',
    'PAGEIND': 'OTHER_FNO',
    'PATANJALI': 'NIFTY_FMCG',
    'PAYTM': 'OTHER_FNO',
    'PCBL': 'NIFTY_CHEMICALS',
    'PERSISTENT': 'NIFTY_IT',
    'PETRONET': 'NIFTY_OIL_AND_GAS',
    'PFC': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'PFOCUS': 'NIFTY_MEDIA',
    'PGEL': 'NIFTY_CONSUMER_DURABLES',
    'PHOENIXLTD': 'NIFTY_REALTY',
    'PIDILITIND': 'NIFTY_CHEMICALS',
    'PIIND': 'NIFTY_CHEMICALS',
    'PNB': 'NIFTY_PSU_BANK',
    'PNBHOUSING': 'OTHER_FNO',
    'POLICYBZR': 'OTHER_FNO',
    'POLYCAB': 'OTHER_FNO',
    'POWERGRID': 'NIFTY_CPSE',
    'POWERINDIA': 'NIFTY_ENERGY',
    'PPLPHARMA': 'NIFTY_PHARMA',
    'PREMIERENE': 'OTHER_FNO',
    'PRESTIGE': 'NIFTY_REALTY',
    'PSB': 'NIFTY_PSU_BANK',
    'PVRINOX': 'NIFTY_MEDIA',
    'RADICO': 'NIFTY_FMCG',
    'RBLBANK': 'NIFTY_PRIVATE_BANK',
    'RECLTD': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'RELIANCE': 'NIFTY_OIL_AND_GAS',
    'RPOWER': 'NIFTY_ENERGY',
    'RVNL': 'NIFTY_PSE',
    'SAGILITY': 'OTHER_FNO',
    'SAIL': 'NIFTY_METAL',
    'SAILIFE': 'NIFTY_PHARMA',
    'SAREGAMA': 'NIFTY_MEDIA',
    'SBICARD': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'SBILIFE': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'SBIN': 'NIFTY_PSU_BANK',
    'SCHAEFFLER': 'NIFTY_MNC',
    'SHREECEM': 'NIFTY_COMMODITIES',
    'SHRIRAMFIN': 'NIFTY_FINANCIAL_SERVICES_25_50',
    'SIEMENS': 'NIFTY_ENERGY',
    'SJVN': 'NIFTY_CPSE',
    'SOBHA': 'NIFTY_REALTY',
    'SOLARINDS': 'NIFTY_CHEMICALS',
    'SONACOMS': 'NIFTY_AUTO',
    'SRF': 'NIFTY_CHEMICALS',
    'SUMICHEM': 'NIFTY_CHEMICALS',
    'SUNPHARMA': 'NIFTY_PHARMA',
    'SUNTV': 'NIFTY_MEDIA',
    'SUPREMEIND': 'OTHER_FNO',
    'SUZLON': 'NIFTY_ENERGY',
    'SWIGGY': 'OTHER_FNO',
    'SYNGENE': 'NIFTY_HEALTHCARE',
    'TATACHEM': 'NIFTY_CHEMICALS',
    'TATACONSUM': 'NIFTY_FMCG',
    'TATAELXSI': 'OTHER_FNO',
    'TATAPOWER': 'NIFTY_COMMODITIES',
    'TATASTEEL': 'NIFTY_METAL',
    'TCS': 'NIFTY_IT',
    'TECHM': 'NIFTY_IT',
    'THERMAX': 'NIFTY_ENERGY',
    'TIINDIA': 'NIFTY_AUTO',
    'TIMKEN': 'NIFTY_MNC',
    'TIPSMUSIC': 'NIFTY_MEDIA',
    'TITAN': 'NIFTY_CONSUMER_DURABLES',
    'TMPV': 'NIFTY_AUTO',
    'TORNTPHARM': 'NIFTY_PHARMA',
    'TORNTPOWER': 'NIFTY_COMMODITIES',
    'TRENT': 'NIFTY_INDIA_CONSUMPTION',
    'TVSMOTOR': 'NIFTY_AUTO',
    'UBL': 'NIFTY_FMCG',
    'UCOBANK': 'NIFTY_PSU_BANK',
    'ULTRACEMCO': 'NIFTY_COMMODITIES',
    'UNIONBANK': 'NIFTY_PSU_BANK',
    'UNITDSPR': 'NIFTY_FMCG',
    'UNOMINDA': 'NIFTY_AUTO',
    'UPL': 'NIFTY_CHEMICALS',
    'VBL': 'NIFTY_FMCG',
    'VEDL': 'NIFTY_METAL',
    'VMM': 'OTHER_FNO',
    'VOLTAS': 'NIFTY_CONSUMER_DURABLES',
    'WAAREEENER': 'OTHER_FNO',
    'WELCORP': 'NIFTY_METAL',
    'WHIRLPOOL': 'NIFTY_CONSUMER_DURABLES',
    'WIPRO': 'NIFTY_IT',
    'WOCKPHARMA': 'NIFTY_PHARMA',
    'YESBANK': 'NIFTY_PRIVATE_BANK',
    'ZEEL': 'NIFTY_MEDIA',
    'ZYDUSLIFE': 'NIFTY_PHARMA',
}

# Every bucket a symbol belongs to (indices overlap by design).
MEMBERSHIP: dict[str, frozenset[str]] = {
    '360ONE': frozenset({'OTHER_FNO'}),
    '3MINDIA': frozenset({'NIFTY_MNC'}),
    'AARTIIND': frozenset({'NIFTY_CHEMICALS'}),
    'ABB': frozenset({'NIFTY_ENERGY', 'NIFTY_MNC'}),
    'ABBOTINDIA': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_MNC', 'NIFTY_PHARMA'}),
    'ABCAPITAL': frozenset({'OTHER_FNO'}),
    'ABREL': frozenset({'NIFTY_REALTY'}),
    'ADANIENSOL': frozenset({'NIFTY_COMMODITIES', 'NIFTY_ENERGY'}),
    'ADANIENT': frozenset({'NIFTY_METAL'}),
    'ADANIGREEN': frozenset({'NIFTY_COMMODITIES', 'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE'}),
    'ADANIPORTS': frozenset({'NIFTY_INFRASTRUCTURE'}),
    'ADANIPOWER': frozenset({'NIFTY_COMMODITIES', 'NIFTY_ENERGY', 'NIFTY_INDIA_CONSUMPTION'}),
    'AEGISLOG': frozenset({'NIFTY_ENERGY', 'NIFTY_OIL_AND_GAS'}),
    'AEGISVOPAK': frozenset({'NIFTY_OIL_AND_GAS'}),
    'AJANTPHARM': frozenset({'NIFTY_PHARMA'}),
    'ALKEM': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'AMBER': frozenset({'NIFTY_CONSUMER_DURABLES'}),
    'AMBUJACEM': frozenset({'NIFTY_COMMODITIES', 'NIFTY_INFRASTRUCTURE', 'NIFTY_MNC'}),
    'ANANTRAJ': frozenset({'NIFTY_REALTY'}),
    'ANGELONE': frozenset({'OTHER_FNO'}),
    'APLAPOLLO': frozenset({'NIFTY_COMMODITIES', 'NIFTY_METAL'}),
    'APOLLOHOSP': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_INDIA_CONSUMPTION', 'NIFTY_INFRASTRUCTURE'}),
    'ASHOKLEY': frozenset({'NIFTY_AUTO', 'NIFTY_INFRASTRUCTURE', 'NIFTY_MNC'}),
    'ASIANPAINT': frozenset({'NIFTY_INDIA_CONSUMPTION'}),
    'ASTRAL': frozenset({'OTHER_FNO'}),
    'ATGL': frozenset({'NIFTY_ENERGY', 'NIFTY_OIL_AND_GAS'}),
    'ATHERENERG': frozenset({'OTHER_FNO'}),
    'ATUL': frozenset({'NIFTY_CHEMICALS'}),
    'AUBANK': frozenset({'NIFTY_BANK'}),
    'AUROPHARMA': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'AWL': frozenset({'NIFTY_MNC'}),
    'AXISBANK': frozenset({'NIFTY_BANK', 'NIFTY_FINANCIAL_SERVICES_25_50', 'NIFTY_PRIVATE_BANK'}),
    'BAJAJ-AUTO': frozenset({'NIFTY_AUTO', 'NIFTY_INDIA_CONSUMPTION'}),
    'BAJAJFINSV': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'BAJAJHLDNG': frozenset({'OTHER_FNO'}),
    'BAJFINANCE': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'BANDHANBNK': frozenset({'NIFTY_PRIVATE_BANK'}),
    'BANKBARODA': frozenset({'NIFTY_BANK', 'NIFTY_PSU_BANK'}),
    'BANKINDIA': frozenset({'NIFTY_PSU_BANK'}),
    'BATAINDIA': frozenset({'NIFTY_CONSUMER_DURABLES'}),
    'BAYERCROP': frozenset({'NIFTY_CHEMICALS'}),
    'BDL': frozenset({'OTHER_FNO'}),
    'BEL': frozenset({'NIFTY_CPSE', 'NIFTY_PSE'}),
    'BHARATFORG': frozenset({'NIFTY_AUTO', 'NIFTY_INFRASTRUCTURE'}),
    'BHARTIARTL': frozenset({'NIFTY_INDIA_CONSUMPTION', 'NIFTY_INFRASTRUCTURE'}),
    'BHEL': frozenset({'NIFTY_ENERGY', 'NIFTY_PSE'}),
    'BIOCON': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'BLUESTARCO': frozenset({'NIFTY_CONSUMER_DURABLES'}),
    'BOSCHLTD': frozenset({'NIFTY_AUTO', 'NIFTY_MNC'}),
    'BPCL': frozenset({'NIFTY_COMMODITIES', 'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE', 'NIFTY_OIL_AND_GAS', 'NIFTY_PSE'}),
    'BRIGADE': frozenset({'NIFTY_REALTY'}),
    'BRITANNIA': frozenset({'NIFTY_FMCG', 'NIFTY_INDIA_CONSUMPTION', 'NIFTY_MNC'}),
    'BSE': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'CAMS': frozenset({'OTHER_FNO'}),
    'CANBK': frozenset({'NIFTY_BANK', 'NIFTY_PSU_BANK'}),
    'CASTROLIND': frozenset({'NIFTY_ENERGY', 'NIFTY_MNC', 'NIFTY_OIL_AND_GAS'}),
    'CDSL': frozenset({'OTHER_FNO'}),
    'CENTRALBK': frozenset({'NIFTY_PSU_BANK'}),
    'CESC': frozenset({'NIFTY_ENERGY'}),
    'CGPOWER': frozenset({'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE'}),
    'CHAMBLFERT': frozenset({'NIFTY_CHEMICALS'}),
    'CHENNPETRO': frozenset({'NIFTY_OIL_AND_GAS'}),
    'CHOLAFIN': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'CIPLA': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'COALINDIA': frozenset({'NIFTY_COMMODITIES', 'NIFTY_CPSE', 'NIFTY_ENERGY', 'NIFTY_PSE'}),
    'COCHINSHIP': frozenset({'NIFTY_CPSE'}),
    'COFORGE': frozenset({'NIFTY_IT'}),
    'COHANCE': frozenset({'NIFTY_MNC'}),
    'COLPAL': frozenset({'NIFTY_FMCG', 'NIFTY_MNC'}),
    'CONCOR': frozenset({'NIFTY_PSE'}),
    'COROMANDEL': frozenset({'NIFTY_CHEMICALS'}),
    'CRISIL': frozenset({'NIFTY_MNC'}),
    'CROMPTON': frozenset({'NIFTY_CONSUMER_DURABLES'}),
    'CUMMINSIND': frozenset({'NIFTY_INFRASTRUCTURE', 'NIFTY_MNC'}),
    'DABUR': frozenset({'NIFTY_FMCG'}),
    'DBCORP': frozenset({'NIFTY_MEDIA'}),
    'DEEPAKNTR': frozenset({'NIFTY_CHEMICALS'}),
    'DELHIVERY': frozenset({'OTHER_FNO'}),
    'DIVISLAB': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'DIXON': frozenset({'NIFTY_CONSUMER_DURABLES', 'NIFTY_INDIA_CONSUMPTION'}),
    'DLF': frozenset({'NIFTY_INDIA_CONSUMPTION', 'NIFTY_INFRASTRUCTURE', 'NIFTY_REALTY'}),
    'DMART': frozenset({'NIFTY_INDIA_CONSUMPTION'}),
    'DRREDDY': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'EICHERMOT': frozenset({'NIFTY_AUTO', 'NIFTY_INDIA_CONSUMPTION'}),
    'EIDPARRY': frozenset({'NIFTY_CHEMICALS'}),
    'EMAMILTD': frozenset({'NIFTY_FMCG'}),
    'ENRIN': frozenset({'NIFTY_ENERGY', 'NIFTY_MNC'}),
    'ESCORTS': frozenset({'NIFTY_MNC'}),
    'ETERNAL': frozenset({'NIFTY_INDIA_CONSUMPTION'}),
    'EXIDEIND': frozenset({'NIFTY_AUTO'}),
    'FEDERALBNK': frozenset({'NIFTY_BANK', 'NIFTY_PRIVATE_BANK'}),
    'FLUOROCHEM': frozenset({'NIFTY_CHEMICALS'}),
    'FORCEMOT': frozenset({'OTHER_FNO'}),
    'FORTIS': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_INFRASTRUCTURE'}),
    'GAIL': frozenset({'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE', 'NIFTY_OIL_AND_GAS', 'NIFTY_PSE'}),
    'GLAND': frozenset({'NIFTY_MNC', 'NIFTY_PHARMA'}),
    'GLENMARK': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'GMRAIRPORT': frozenset({'OTHER_FNO'}),
    'GNFC': frozenset({'NIFTY_CHEMICALS'}),
    'GODFRYPHLP': frozenset({'OTHER_FNO'}),
    'GODREJCP': frozenset({'NIFTY_FMCG', 'NIFTY_INDIA_CONSUMPTION'}),
    'GODREJPROP': frozenset({'NIFTY_REALTY'}),
    'GRASIM': frozenset({'NIFTY_COMMODITIES', 'NIFTY_INFRASTRUCTURE'}),
    'GVT&D': frozenset({'NIFTY_ENERGY'}),
    'HAL': frozenset({'NIFTY_PSE'}),
    'HATHWAY': frozenset({'NIFTY_MEDIA'}),
    'HAVELLS': frozenset({'NIFTY_CONSUMER_DURABLES', 'NIFTY_INDIA_CONSUMPTION'}),
    'HCLTECH': frozenset({'NIFTY_IT'}),
    'HDFCAMC': frozenset({'OTHER_FNO'}),
    'HDFCBANK': frozenset({'NIFTY_BANK', 'NIFTY_FINANCIAL_SERVICES_25_50', 'NIFTY_PRIVATE_BANK'}),
    'HDFCLIFE': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'HEROMOTOCO': frozenset({'NIFTY_AUTO', 'NIFTY_INDIA_CONSUMPTION'}),
    'HINDALCO': frozenset({'NIFTY_COMMODITIES', 'NIFTY_METAL'}),
    'HINDCOPPER': frozenset({'NIFTY_METAL'}),
    'HINDPETRO': frozenset({'NIFTY_COMMODITIES', 'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE', 'NIFTY_OIL_AND_GAS', 'NIFTY_PSE'}),
    'HINDUNILVR': frozenset({'NIFTY_FMCG', 'NIFTY_INDIA_CONSUMPTION', 'NIFTY_MNC'}),
    'HINDZINC': frozenset({'NIFTY_METAL'}),
    'HSCL': frozenset({'NIFTY_CHEMICALS'}),
    'HYUNDAI': frozenset({'NIFTY_MNC'}),
    'ICICIBANK': frozenset({'NIFTY_BANK', 'NIFTY_FINANCIAL_SERVICES_25_50', 'NIFTY_PRIVATE_BANK'}),
    'ICICIGI': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'ICICIPRULI': frozenset({'OTHER_FNO'}),
    'IDEA': frozenset({'OTHER_FNO'}),
    'IDFCFIRSTB': frozenset({'NIFTY_BANK', 'NIFTY_PRIVATE_BANK'}),
    'IEX': frozenset({'OTHER_FNO'}),
    'IGL': frozenset({'NIFTY_ENERGY', 'NIFTY_OIL_AND_GAS'}),
    'INDHOTEL': frozenset({'NIFTY_INDIA_CONSUMPTION', 'NIFTY_INFRASTRUCTURE'}),
    'INDIANB': frozenset({'NIFTY_PSU_BANK'}),
    'INDIGO': frozenset({'NIFTY_INDIA_CONSUMPTION', 'NIFTY_INFRASTRUCTURE'}),
    'INDUSINDBK': frozenset({'NIFTY_BANK', 'NIFTY_PRIVATE_BANK'}),
    'INDUSTOWER': frozenset({'NIFTY_INFRASTRUCTURE'}),
    'INFY': frozenset({'NIFTY_IT'}),
    'INOXWIND': frozenset({'NIFTY_ENERGY'}),
    'IOB': frozenset({'NIFTY_PSU_BANK'}),
    'IOC': frozenset({'NIFTY_COMMODITIES', 'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE', 'NIFTY_OIL_AND_GAS', 'NIFTY_PSE'}),
    'IPCALAB': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'IRCTC': frozenset({'NIFTY_PSE'}),
    'IREDA': frozenset({'OTHER_FNO'}),
    'IRFC': frozenset({'NIFTY_PSE'}),
    'ITC': frozenset({'NIFTY_FMCG', 'NIFTY_INDIA_CONSUMPTION'}),
    'JINDALSTEL': frozenset({'NIFTY_COMMODITIES', 'NIFTY_METAL'}),
    'JIOFIN': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'JPPOWER': frozenset({'NIFTY_ENERGY'}),
    'JSL': frozenset({'NIFTY_METAL'}),
    'JSWENERGY': frozenset({'NIFTY_COMMODITIES', 'NIFTY_ENERGY'}),
    'JSWSTEEL': frozenset({'NIFTY_COMMODITIES', 'NIFTY_METAL'}),
    'JUBLFOOD': frozenset({'OTHER_FNO'}),
    'KAJARIACER': frozenset({'NIFTY_CONSUMER_DURABLES'}),
    'KALYANKJIL': frozenset({'NIFTY_CONSUMER_DURABLES'}),
    'KAYNES': frozenset({'OTHER_FNO'}),
    'KEI': frozenset({'OTHER_FNO'}),
    'KFINTECH': frozenset({'OTHER_FNO'}),
    'KOTAKBANK': frozenset({'NIFTY_BANK', 'NIFTY_FINANCIAL_SERVICES_25_50', 'NIFTY_PRIVATE_BANK'}),
    'KPITTECH': frozenset({'OTHER_FNO'}),
    'LAURUSLABS': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'LGEINDIA': frozenset({'NIFTY_CONSUMER_DURABLES'}),
    'LICHSGFIN': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'LICI': frozenset({'OTHER_FNO'}),
    'LINDEINDIA': frozenset({'NIFTY_CHEMICALS', 'NIFTY_MNC'}),
    'LLOYDSME': frozenset({'NIFTY_METAL'}),
    'LODHA': frozenset({'NIFTY_REALTY'}),
    'LT': frozenset({'NIFTY_INFRASTRUCTURE'}),
    'LTF': frozenset({'OTHER_FNO'}),
    'LTM': frozenset({'NIFTY_IT'}),
    'LUPIN': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'M&M': frozenset({'NIFTY_AUTO', 'NIFTY_INDIA_CONSUMPTION'}),
    'MAHABANK': frozenset({'NIFTY_PSU_BANK'}),
    'MANAPPURAM': frozenset({'OTHER_FNO'}),
    'MANKIND': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'MARICO': frozenset({'NIFTY_FMCG'}),
    'MARUTI': frozenset({'NIFTY_AUTO', 'NIFTY_INDIA_CONSUMPTION', 'NIFTY_MNC'}),
    'MAXHEALTH': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_INDIA_CONSUMPTION', 'NIFTY_INFRASTRUCTURE'}),
    'MAZDOCK': frozenset({'OTHER_FNO'}),
    'MCX': frozenset({'OTHER_FNO'}),
    'MFSL': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'MGL': frozenset({'NIFTY_ENERGY', 'NIFTY_OIL_AND_GAS'}),
    'MOTHERSON': frozenset({'NIFTY_AUTO', 'NIFTY_INFRASTRUCTURE'}),
    'MOTILALOFS': frozenset({'OTHER_FNO'}),
    'MPHASIS': frozenset({'NIFTY_IT'}),
    'MUTHOOTFIN': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'NAM-INDIA': frozenset({'NIFTY_MNC'}),
    'NATIONALUM': frozenset({'NIFTY_METAL'}),
    'NAUKRI': frozenset({'NIFTY_INDIA_CONSUMPTION'}),
    'NAVA': frozenset({'NIFTY_ENERGY'}),
    'NAVINFLUOR': frozenset({'NIFTY_CHEMICALS'}),
    'NAZARA': frozenset({'NIFTY_MEDIA'}),
    'NBCC': frozenset({'NIFTY_CPSE'}),
    'NESTLEIND': frozenset({'NIFTY_FMCG', 'NIFTY_INDIA_CONSUMPTION', 'NIFTY_MNC'}),
    'NETWORK18': frozenset({'NIFTY_MEDIA'}),
    'NHPC': frozenset({'NIFTY_COMMODITIES', 'NIFTY_CPSE', 'NIFTY_ENERGY', 'NIFTY_PSE'}),
    'NLCINDIA': frozenset({'NIFTY_CPSE', 'NIFTY_ENERGY'}),
    'NMDC': frozenset({'NIFTY_COMMODITIES', 'NIFTY_METAL', 'NIFTY_PSE'}),
    'NTPC': frozenset({'NIFTY_COMMODITIES', 'NIFTY_CPSE', 'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE', 'NIFTY_PSE'}),
    'NTPCGREEN': frozenset({'NIFTY_ENERGY'}),
    'NYKAA': frozenset({'OTHER_FNO'}),
    'OBEROIRLTY': frozenset({'NIFTY_REALTY'}),
    'OFSS': frozenset({'NIFTY_IT', 'NIFTY_MNC'}),
    'OIL': frozenset({'NIFTY_COMMODITIES', 'NIFTY_CPSE', 'NIFTY_ENERGY', 'NIFTY_OIL_AND_GAS', 'NIFTY_PSE'}),
    'ONGC': frozenset({'NIFTY_COMMODITIES', 'NIFTY_CPSE', 'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE', 'NIFTY_OIL_AND_GAS', 'NIFTY_PSE'}),
    'PAGEIND': frozenset({'OTHER_FNO'}),
    'PATANJALI': frozenset({'NIFTY_FMCG'}),
    'PAYTM': frozenset({'OTHER_FNO'}),
    'PCBL': frozenset({'NIFTY_CHEMICALS'}),
    'PERSISTENT': frozenset({'NIFTY_IT'}),
    'PETRONET': frozenset({'NIFTY_ENERGY', 'NIFTY_OIL_AND_GAS'}),
    'PFC': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50', 'NIFTY_PSE'}),
    'PFOCUS': frozenset({'NIFTY_MEDIA'}),
    'PGEL': frozenset({'NIFTY_CONSUMER_DURABLES'}),
    'PHOENIXLTD': frozenset({'NIFTY_REALTY'}),
    'PIDILITIND': frozenset({'NIFTY_CHEMICALS', 'NIFTY_COMMODITIES'}),
    'PIIND': frozenset({'NIFTY_CHEMICALS', 'NIFTY_COMMODITIES'}),
    'PNB': frozenset({'NIFTY_BANK', 'NIFTY_PSU_BANK'}),
    'PNBHOUSING': frozenset({'OTHER_FNO'}),
    'POLICYBZR': frozenset({'OTHER_FNO'}),
    'POLYCAB': frozenset({'OTHER_FNO'}),
    'POWERGRID': frozenset({'NIFTY_CPSE', 'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE', 'NIFTY_PSE'}),
    'POWERINDIA': frozenset({'NIFTY_ENERGY', 'NIFTY_MNC'}),
    'PPLPHARMA': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'PREMIERENE': frozenset({'OTHER_FNO'}),
    'PRESTIGE': frozenset({'NIFTY_REALTY'}),
    'PSB': frozenset({'NIFTY_PSU_BANK'}),
    'PVRINOX': frozenset({'NIFTY_MEDIA'}),
    'RADICO': frozenset({'NIFTY_FMCG'}),
    'RBLBANK': frozenset({'NIFTY_PRIVATE_BANK'}),
    'RECLTD': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50', 'NIFTY_PSE'}),
    'RELIANCE': frozenset({'NIFTY_COMMODITIES', 'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE', 'NIFTY_OIL_AND_GAS'}),
    'RPOWER': frozenset({'NIFTY_ENERGY'}),
    'RVNL': frozenset({'NIFTY_PSE'}),
    'SAGILITY': frozenset({'OTHER_FNO'}),
    'SAIL': frozenset({'NIFTY_METAL'}),
    'SAILIFE': frozenset({'NIFTY_PHARMA'}),
    'SAREGAMA': frozenset({'NIFTY_MEDIA'}),
    'SBICARD': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'SBILIFE': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'SBIN': frozenset({'NIFTY_BANK', 'NIFTY_FINANCIAL_SERVICES_25_50', 'NIFTY_PSU_BANK'}),
    'SCHAEFFLER': frozenset({'NIFTY_MNC'}),
    'SHREECEM': frozenset({'NIFTY_COMMODITIES', 'NIFTY_INFRASTRUCTURE'}),
    'SHRIRAMFIN': frozenset({'NIFTY_FINANCIAL_SERVICES_25_50'}),
    'SIEMENS': frozenset({'NIFTY_ENERGY', 'NIFTY_MNC'}),
    'SJVN': frozenset({'NIFTY_CPSE', 'NIFTY_ENERGY'}),
    'SOBHA': frozenset({'NIFTY_REALTY'}),
    'SOLARINDS': frozenset({'NIFTY_CHEMICALS'}),
    'SONACOMS': frozenset({'NIFTY_AUTO'}),
    'SRF': frozenset({'NIFTY_CHEMICALS', 'NIFTY_COMMODITIES'}),
    'SUMICHEM': frozenset({'NIFTY_CHEMICALS'}),
    'SUNPHARMA': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'SUNTV': frozenset({'NIFTY_MEDIA'}),
    'SUPREMEIND': frozenset({'OTHER_FNO'}),
    'SUZLON': frozenset({'NIFTY_ENERGY', 'NIFTY_INFRASTRUCTURE'}),
    'SWIGGY': frozenset({'OTHER_FNO'}),
    'SYNGENE': frozenset({'NIFTY_HEALTHCARE'}),
    'TATACHEM': frozenset({'NIFTY_CHEMICALS'}),
    'TATACONSUM': frozenset({'NIFTY_FMCG', 'NIFTY_INDIA_CONSUMPTION'}),
    'TATAELXSI': frozenset({'OTHER_FNO'}),
    'TATAPOWER': frozenset({'NIFTY_COMMODITIES', 'NIFTY_ENERGY', 'NIFTY_INDIA_CONSUMPTION', 'NIFTY_INFRASTRUCTURE'}),
    'TATASTEEL': frozenset({'NIFTY_COMMODITIES', 'NIFTY_METAL'}),
    'TCS': frozenset({'NIFTY_IT'}),
    'TECHM': frozenset({'NIFTY_IT'}),
    'THERMAX': frozenset({'NIFTY_ENERGY'}),
    'TIINDIA': frozenset({'NIFTY_AUTO'}),
    'TIMKEN': frozenset({'NIFTY_MNC'}),
    'TIPSMUSIC': frozenset({'NIFTY_MEDIA'}),
    'TITAN': frozenset({'NIFTY_CONSUMER_DURABLES', 'NIFTY_INDIA_CONSUMPTION'}),
    'TMPV': frozenset({'NIFTY_AUTO'}),
    'TORNTPHARM': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
    'TORNTPOWER': frozenset({'NIFTY_COMMODITIES', 'NIFTY_ENERGY'}),
    'TRENT': frozenset({'NIFTY_INDIA_CONSUMPTION'}),
    'TVSMOTOR': frozenset({'NIFTY_AUTO', 'NIFTY_INDIA_CONSUMPTION'}),
    'UBL': frozenset({'NIFTY_FMCG', 'NIFTY_MNC'}),
    'UCOBANK': frozenset({'NIFTY_PSU_BANK'}),
    'ULTRACEMCO': frozenset({'NIFTY_COMMODITIES', 'NIFTY_INFRASTRUCTURE'}),
    'UNIONBANK': frozenset({'NIFTY_BANK', 'NIFTY_PSU_BANK'}),
    'UNITDSPR': frozenset({'NIFTY_FMCG', 'NIFTY_INDIA_CONSUMPTION', 'NIFTY_MNC'}),
    'UNOMINDA': frozenset({'NIFTY_AUTO'}),
    'UPL': frozenset({'NIFTY_CHEMICALS', 'NIFTY_COMMODITIES'}),
    'VBL': frozenset({'NIFTY_FMCG', 'NIFTY_INDIA_CONSUMPTION'}),
    'VEDL': frozenset({'NIFTY_COMMODITIES', 'NIFTY_METAL', 'NIFTY_MNC'}),
    'VMM': frozenset({'OTHER_FNO'}),
    'VOLTAS': frozenset({'NIFTY_CONSUMER_DURABLES'}),
    'WAAREEENER': frozenset({'OTHER_FNO'}),
    'WELCORP': frozenset({'NIFTY_METAL'}),
    'WHIRLPOOL': frozenset({'NIFTY_CONSUMER_DURABLES'}),
    'WIPRO': frozenset({'NIFTY_IT'}),
    'WOCKPHARMA': frozenset({'NIFTY_PHARMA'}),
    'YESBANK': frozenset({'NIFTY_BANK', 'NIFTY_PRIVATE_BANK'}),
    'ZEEL': frozenset({'NIFTY_MEDIA'}),
    'ZYDUSLIFE': frozenset({'NIFTY_HEALTHCARE', 'NIFTY_PHARMA'}),
}


def stocks_in(bucket: str) -> frozenset[str]:
    """Every constituent of a bucket."""
    return ALL_BUCKETS[bucket]


def fno_in(bucket: str) -> frozenset[str]:
    """Constituents of a bucket that have a futures contract."""
    return ALL_BUCKETS[bucket] & FNO_STOCKS


def non_fno_in(bucket: str) -> frozenset[str]:
    """Constituents of a bucket that are cash-only."""
    return ALL_BUCKETS[bucket] - FNO_STOCKS


def buckets_of(symbol: str) -> frozenset[str]:
    """Every bucket a symbol belongs to; empty if it is not in the universe."""
    return MEMBERSHIP.get(symbol.strip().upper(), frozenset())


def sectoral_names() -> tuple[str, ...]:
    return tuple(SECTORAL_BUCKETS)


def thematic_names() -> tuple[str, ...]:
    return tuple(THEMATIC_BUCKETS)


def is_fno(symbol: str) -> bool:
    return symbol.strip().upper() in FNO_STOCKS
