@echo off
setlocal

cd /d "%~dp0.."
set EQIDV2_ENTRY_ENGINE_1MIN_V5_ID_DELAY_SEC=60
set EQIDV2_ENTRY_ENGINE_1MIN_V5_ID_DUE_GRACE_SEC=90
set EQIDV2_ENTRY_ENGINE_1MIN_V5_ID_POLL_SEC=1
set EQIDV2_ENTRY_ENGINE_1MIN_V7_MAX_DELAY_MIN=5

python eqidv2_entry_engine_1min_v5_id.py

endlocal
