@echo off
setlocal

cd /d "%~dp0.."
set "EQIDV2_RUNTIME_ROOT=C:\TradingData\eqidv2"
set "EQIDV2_DATA_5M_DIR=C:\TradingData\eqidv2\stocks_indicators_5min_eq_live"
set "EQIDV2_DATA_1MIN_DIR=C:\TradingData\eqidv2\stocks_indicators_1min_eq"
set EQIDV2_ENTRY_ENGINE_1MIN_V5_ID_DELAY_SEC=60
set EQIDV2_ID5MIN_V7_MAX_ENTRY_TO_DETECTION_LAG_SEC=75
set EQIDV2_ENTRY_ENGINE_1MIN_V5_ID_DUE_GRACE_SEC=15
set EQIDV2_ENTRY_ENGINE_1MIN_V5_ID_PROCESS_RESERVE_SEC=5
set EQIDV2_ENTRY_ENGINE_1MIN_V5_ID_POLL_SEC=1
set EQIDV2_ENTRY_ENGINE_1MIN_V7_MAX_DELAY_MIN=5
set EQIDV2_ENTRY_ENGINE_PRE_MOMENTUM_GATES=1
set EQIDV2_ENTRY_ENGINE_PRE_MOMENTUM_MISSING_ACTION=allow

python eqidv2_entry_engine_1min_v5_id.py

endlocal
